language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
install:
    - pip install .
before_script:
    - cd test
    - pip install -r requirements_test.txt
script:
    - coverage run --source f90nml test_f90nml.py
after_success:
    - coverage report -m
    - coveralls
sudo: False
